name: Deploy to VPS
on:
  workflow_dispatch:
    branches:
      - main
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn --frozen-lockfile install
      - name: Build application
        run: yarn build
      - name: Deploy migrations
        run: yarn prisma:deploy
      - name: SCP dist folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: 'node_modules,dist/*'
          target: '/home/github/expense-api'
      - name: PM2 restart
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: >
            DATABASE_URL=${{ secrets.DATABSE_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            pm2 reload /home/${{ secrets.USERNAME }}/expense-api/dist/src/main.js
            ||
            DATABASE_URL=${{ secrets.DATABSE_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            pm2 start /home/${{ secrets.USERNAME }}/expense-api/dist/src/main.js
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
